# Generated by Django 6.0 on 2025-12-17 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('id_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PASSPORT', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], max_length=20, verbose_name='Tipo de Identificación')),
                ('id_number', models.CharField(max_length=50, verbose_name='Número de Identificación')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('profile_photo_url', models.URLField(blank=True, null=True, verbose_name='URL Foto de Perfil')),
                ('email_primary', models.EmailField(max_length=254, unique=True, verbose_name='Email Principal')),
                ('email_secondary', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Secundario')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENT', 'Cliente'), ('INTERVENTORIA', 'Interventoría'), ('SUPERVISOR', 'Supervisor')], default='CLIENT', max_length=20, verbose_name='Rol')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Inicio de Sesión')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'indexes': [models.Index(fields=['email_primary'], name='users_user_email_p_e96e73_idx'), models.Index(fields=['role', 'status'], name='users_user_role_6e67fb_idx'), models.Index(fields=['id_type', 'id_number'], name='users_user_id_type_aba6ba_idx')],
                'unique_together': {('id_type', 'id_number')},
            },
        ),
    ]
