"""
Constants for audit log actions.
"""
# Authentication actions
LOGIN_SUCCESS = 'LOGIN_SUCCESS'
LOGIN_FAILED = 'LOGIN_FAILED'
LOGOUT = 'LOGOUT'

# User management actions
USER_REGISTERED = 'USER_REGISTERED'
USER_CREATED_BY_ADMIN = 'USER_CREATED_BY_ADMIN'
USER_UPDATED_BY_ADMIN = 'USER_UPDATED_BY_ADMIN'
USER_UPDATED_SELF = 'USER_UPDATED_SELF'
USER_SUSPENDED = 'USER_SUSPENDED'
USER_ACTIVATED = 'USER_ACTIVATED'
USER_DELETED = 'USER_DELETED'

# Policy actions (for future use)
POLICY_CREATED = 'POLICY_CREATED'
POLICY_UPDATED = 'POLICY_UPDATED'
POLICY_DELETED = 'POLICY_DELETED'

# Payment actions (for future use)
PAYMENT_CREATED = 'PAYMENT_CREATED'
PAYMENT_COMPLETED = 'PAYMENT_COMPLETED'
PAYMENT_FAILED = 'PAYMENT_FAILED'

