# Generated by Django 6.0 on 2025-12-17 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Tipo de acción realizada (ej: LOGIN_SUCCESS, USER_CREATED)', max_length=100, verbose_name='Acción')),
                ('entity', models.CharField(help_text='Entidad afectada (ej: User, Policy)', max_length=50, verbose_name='Entidad')),
                ('entity_id', models.UUIDField(blank=True, help_text='ID de la entidad afectada', null=True, verbose_name='ID de Entidad')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la acción', null=True, verbose_name='Metadatos')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del cliente que realizó la acción', null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actor')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['entity'], name='audit_audit_entity_845d0e_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['actor_user'], name='audit_audit_actor_u_3f83e1_idx'), models.Index(fields=['entity', 'entity_id'], name='audit_audit_entity_8edb54_idx')],
            },
        ),
    ]
